name: linkrunner
description: "Flutter Package for linkrunner, track every click, download and dropoff for your app links"
version: 3.6.0
homepage: "https://www.linkrunner.io/"
repository: "https://github.com/RathodDarshil/linkrunner_flutter"
documentation: "https://github.com/RathodDarshil/linkrunner_flutter#getting-started"
topics:
    - linkrunner
    - app-attribution
    - app-link-tracking
    - app-tracking
    - tracking

environment:
    sdk: ">=3.3.0 <4.0.0"
    flutter: ">=3.19.0"

dependencies:
    flutter:
        sdk: flutter

flutter:
    plugin:
        platforms:
            android:
                package: io.linkrunner.flutter
                pluginClass: LinkrunnerPlugin
            ios:
                pluginClass: LinkrunnerPlugin

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
